version: '3.7'

services:

  movie_service:
    build: ./../movie-service
    command: python3 /movie-service/main.py &
    volumes:
      - ./../movie-service/:/movie-service/
    ports:
      - 8000:8000
    environment:
      - env=test
    container_name: movie-service-app

  movie_db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=movie_db_username
      - POSTGRES_PASSWORD=movie_db_password
      - POSTGRES_DB=movie_db_dev
    container_name: movie-service-db-compose

volumes:
  postgres_data_movie: