version: '3.7'

services:
  movie_db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=movie_db_username
      - POSTGRES_PASSWORD=movie_db_password
      - POSTGRES_DB=movie_db_dev
    container_name: movie-service-db

volumes:
  postgres_data_movie: